In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv"
df = pd.read_csv(url)
df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

In [2]:
df[df['tenure'] == 0]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [4]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [5]:
# (df['TotalCharges'] == ' ').sum()

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [6]:
df['Churn'].value_counts(normalize=True)

Churn
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

In [7]:
df['TotalCharges'] = df['TotalCharges'].fillna(df['MonthlyCharges'])

df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [8]:
df['TotalServices'] = df[['OnlineBackup', 'OnlineSecurity', 'PhoneService', 'StreamingMovies', 'StreamingTV', 'TechSupport', 'DeviceProtection']].eq('Yes').sum(axis=1)

df['TenureCategory'] = pd.cut(
    df['tenure'],
    bins = [0, 5, 11, 23, 47, 100],
    labels= ['New', 'Developing', 'Established', 'Loyal', 'Vetran']
)

df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TotalServices,TenureCategory
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1,New
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.50,No,3,Loyal
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,3,New
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,3,Loyal
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No,6,Loyal
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,5,Vetran
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,1,Developing
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,1,New
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,6,Vetran

In [9]:
# df.columns

featurs = [
    'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'TenureCategory', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalServices', 'TotalCharges'
]

data = df[featurs + ['Churn']].copy()
data = pd.get_dummies(data, columns=[
    'TenureCategory', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod'], drop_first=True)
data

,MonthlyCharges,TotalServices,TotalCharges,Churn,TenureCategory_Developing,TenureCategory_Established,TenureCategory_Loyal,TenureCategory_Vetran,gender_Male,SeniorCitizen_1,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,29.85,1,29.85,No,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
1,56.95,3,1889.50,No,False,False,True,False,True,False,...,False,False,False,False,True,False,False,False,False,True
2,53.85,3,108.15,Yes,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,True
3,42.30,3,1840.75,No,False,False,True,False,True,False,...,False,False,False,False,True,False,False,False,False,False
4,70.70,1,151.65,Yes,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,84.80,6,1990.50,No,False,False,True,False,True,False,...,False,True,False,True,True,False,True,False,False,True
7039,103.20,5,7362.90,No,False,False,False,True,False,False,...,False,True,False,True,True,False,True,True,False,False
7040,29.60,1,346.45,No,True,False,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
7041,74.40,1,306.60,Yes,False,False,False,False,True,True,...,False,False,False,False,False,False,True,False,False,True
7042,105.65,6,6844.50,No,False,False,False,True,True,False,...,False,True,False,True,False,True,True,False,False,False

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 35 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   MonthlyCharges                         7043 non-null   float64
 1   TotalServices                          7043 non-null   int64
 2   TotalCharges                           7043 non-null   float64
 3   Churn                                  7043 non-null   object
 4   TenureCategory_Developing              7043 non-null   bool
 5   TenureCategory_Established             7043 non-null   bool
 6   TenureCategory_Loyal                   7043 non-null   bool
 7   TenureCategory_Vetran                  7043 non-null   bool
 8   gender_Male                            7043 non-null   bool
 9   SeniorCitizen_1                        7043 non-null   bool
 10  Partner_Yes                            7043 non-null   bool
 11  Dependents_Yes                         7043 non-null   bool
 12  PhoneService_Yes                       7043 non-null   bool
 13  MultipleLines_No phone service         7043 non-null   bool
 14  MultipleLines_Yes                      7043 non-null   bool
 15  InternetService_Fiber optic            7043 non-null   bool
 16  InternetService_No                     7043 non-null   bool
 17  OnlineSecurity_No internet service     7043 non-null   bool
 18  OnlineSecurity_Yes                     7043 non-null   bool
 19  OnlineBackup_No internet service       7043 non-null   bool
 20  OnlineBackup_Yes                       7043 non-null   bool
 21  DeviceProtection_No internet service   7043 non-null   bool
 22  DeviceProtection_Yes                   7043 non-null   bool
 23  TechSupport_No internet service        7043 non-null   bool
 24  TechSupport_Yes                        7043 non-null   bool
 25  StreamingTV_No internet service        7043 non-null   bool
 26  StreamingTV_Yes                        7043 non-null   bool
 27  StreamingMovies_No internet service    7043 non-null   bool
 28  StreamingMovies_Yes                    7043 non-null   bool
 29  Contract_One year                      7043 non-null   bool
 30  Contract_Two year                      7043 non-null   bool
 31  PaperlessBilling_Yes                   7043 non-null   bool
 32  PaymentMethod_Credit card (automatic)  7043 non-null   bool
 33  PaymentMethod_Electronic check         7043 non-null   bool
 34  PaymentMethod_Mailed check             7043 non-null   bool
dtypes: bool(31), float64(2), int64(1), object(1)
memory usage: 433.4+ KB

In [11]:
from sklearn.model_selection import train_test_split

X = data.drop('Churn', axis=1)
y = (data['Churn'] == "Yes").astype(int)

X.isna().sum()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

log_re = LogisticRegression(max_iter=10000, class_weight='balanced').fit(X_train, y_train)

rf_cl = RandomForestClassifier(random_state=42, class_weight='balanced').fit(X_train, y_train)

In [13]:
res_log = log_re.predict(X_test)
res_rf =  rf_cl.predict(X_test)

print("LogisticRegression Result:")
print(confusion_matrix(y_test, res_log))
print(classification_report(y_test, res_log))

print("RandomForestClassifier Result:")
print(confusion_matrix(y_test, res_rf))
print(classification_report(y_test, res_rf))

LogisticRegression Result:
[[761 275]
 [ 68 305]]
              precision    recall  f1-score   support

           0       0.92      0.73      0.82      1036
           1       0.53      0.82      0.64       373

    accuracy                           0.76      1409
   macro avg       0.72      0.78      0.73      1409
weighted avg       0.81      0.76      0.77      1409

RandomForestClassifier Result:
[[944  92]
 [197 176]]
              precision    recall  f1-score   support

           0       0.83      0.91      0.87      1036
           1       0.66      0.47      0.55       373

    accuracy                           0.79      1409
   macro avg       0.74      0.69      0.71      1409
weighted avg       0.78      0.79      0.78      1409

In [14]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [4, 6, 8, None],
    'min_samples_split': [2, 5, 10]
}

grid_search = GridSearchCV(
    estimator= RandomForestClassifier(random_state=42, class_weight='balanced'),
    param_grid= param_grid,
    cv= 5,
    scoring= 'recall',
    n_jobs = -1
)

grid_search.fit(X_train,y_train)

print(f"Best Parameter: {grid_search.best_params_}")
print(f"Best Score: {grid_search.best_score_}")

Best Parameter: {'max_depth': 4, 'min_samples_split': 2, 'n_estimators': 100}
Best Score: 0.8155161649944258

In [15]:
best_model = grid_search.best_estimator_
grid_best_pred = best_model.predict(X_test)

print("Confsion matrix:\n", confusion_matrix(y_test, grid_best_pred))
print("Classification Report:\n", classification_report(y_test, grid_best_pred))

Confsion matrix:
 [[708 328]
 [ 57 316]]
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.68      0.79      1036
           1       0.49      0.85      0.62       373

    accuracy                           0.73      1409
   macro avg       0.71      0.77      0.70      1409
weighted avg       0.81      0.73      0.74      1409

In [16]:
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100]
}

grid_model = GridSearchCV(
    estimator= LogisticRegression(max_iter=10000, class_weight='balanced'),
    param_grid= param_grid,
    cv= 5,
    scoring='recall',
    n_jobs = -1
)

grid_model.fit(X_train,y_train)

print(f"Best Parameter: {grid_model.best_params_}")
print(f"Best Score: {grid_model.best_score_}")

Best Parameter: {'C': 100}
Best Score: 0.7947848383500558

In [17]:
best_log_model = grid_model.best_estimator_
log_grid_pred = best_log_model.predict(X_test)

print("Confsion matrix:\n", confusion_matrix(y_test, log_grid_pred))
print("Classification Report:\n", classification_report(y_test, log_grid_pred))

Confsion matrix:
 [[758 278]
 [ 66 307]]
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.73      0.82      1036
           1       0.52      0.82      0.64       373

    accuracy                           0.76      1409
   macro avg       0.72      0.78      0.73      1409
weighted avg       0.82      0.76      0.77      1409

In [18]:
import joblib

#save the trained model
joblib.dump(best_log_model, 'churn_model.pkl')

#saves the exact column structure the model expects (excludthe target colunm)
model_colunms = data.drop('Churn', axis=1).columns.tolist()
joblib.dump(model_colunms, 'model_columns.pkl')

['model_columns.pkl']

In [19]:
import os
print(os.path.getsize('churn_model.pkl'), 'bytes')
loaded_columns = joblib.load('model_columns.pkl')
print(len(loaded_columns), loaded_columns[:5])

2239 bytes
34 ['MonthlyCharges', 'TotalServices', 'TotalCharges', 'TenureCategory_Developing', 'TenureCategory_Established']

In [20]:
result = pd.cut([12], bins=[0, 5, 11, 23, 47, 100], labels=['New', 'Developing', 'Established', 'Loyal', 'Vetran'])
print(result, type(result))

['Established']
Categories (5, object): ['New' < 'Developing' < 'Established' < 'Loyal' < 'Vetran'] <class 'pandas.core.arrays.categorical.Categorical'>

In [21]:
# a single customer's raw data, after get_dummies would only produce SOME columns
one_customer = pd.DataFrame([{
    'Contract': 'Two year',
    'gender': 'male'
}])

dummied = pd.get_dummies(one_customer, columns=['Contract', 'gender'])
print(dummied)

   Contract_Two year  gender_male
0               True         True

In [22]:
expected_columns = ['Contract_One year', 'Contract_Two year', 'gender_male']

fixed = dummied.reindex(columns=expected_columns, fill_value=0)
print(fixed)

   Contract_One year  Contract_Two year  gender_male
0                  0               True         True

In [23]:
print(log_grid_pred)

[1 0 0 ... 0 0 1]

In [24]:
import sys
print(sys.version)

3.13.15 (main, Aug  6 2026, 11:06:23) [GCC 11.4.0]

In [25]:
print(best_log_model.predict_proba(X_test))

[[0.14853944 0.85146056]
 [0.76678042 0.23321958]
 [0.97773327 0.02226673]
 ...
 [0.90678161 0.09321839]
 [0.91069353 0.08930647]
 [0.28599086 0.71400914]]

In [26]:
df[df['tenure'] == 0]['Churn'].value_counts(normalize=True)

Churn
No    1.0
Name: proportion, dtype: float64